name: test output workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  outputtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - id: devcontainer-build
        name: Execute DevContainer commands
        uses: devcontainers/ci@v0.3.1900000349
        with: 
          runCmd: |
            echo "foo=bar" >> $GITHUB_OUTPUT

      - name: get output
        run: |
          set -e
          echo "Test output.."
          echo "${{ steps.devcontainer-build.outputs.foo }}"
          echo "Value printed and action completes.."

  nextvaluetest:
    runs-on: ubuntu-latest
    needs: outputtest
    steps:
      - uses: actions/checkout@v4

      - name: get prev output
        run: |
          set -e
          echo "Previous job output.."
          echo "${{ needs.outputtest.outputs.foo }}"
          echo "Previous job value printed and action completes.."
